MACOSX_DEPLOYMENT_TARGET:  # [osx and x86_64]
  - "10.14"                # [osx and x86_64]
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - "10.14"                # [osx and x86_64]

cxx_compiler_version:  # [osx]
    - 14               # [osx]

hoomd:
  - v2
  - v3
  - v4
